---
title: "test.RMD"
author: "Christian A."
date: "`r Sys.Date()`"
output: html_document
---
```{r setup, eval = TRUE}
knitr::opts_chunk$set(cache = TRUE)

```

```{r}
x = rnorm(10)

plot(x, pch = 19, col = "dodgerblue")

```

```{r }
y = rbinom(20, size = 1, prob = .5)
table(y)


```


```{r}

library(Biobase)
library(GenomicRanges)
data("sample.ExpressionSet", package = "Biobase")
se = makeSummarizedExperimentFromExpressionSet(sample.ExpressionSet)

```

```{r}
con = url("http://bowtie-bio.sourceforge.net/recount/ExpressionSets/bottomly_eset.RData")
load(file = con)
close(con)
bot = bottomly.eset
pdata_bot = pData(bot)

con = url("http://bowtie-bio.sourceforge.net/recount/ExpressionSets/bodymap_eset.RData")
load(file = con)
close(con)
bm = bodymap.eset
pdata_bm = pData(bm)
edata_bm = exprs(bm)

```

```{R }
library(plotrix)
pie3D(pdata_bm$num.tech.reps,labels=pdata_bm$tissue.type)
```



```{r}
mm = log2(edata_bm[,1]+1) - log2(edata_bm[,2]+1)
aa = log2(edata_bm[,1]+1) + log2(edata_bm[,2]+1)
plot(aa,mm,col=2)
abline(h=0)

```

```{r}
con = url("http://bowtie-bio.sourceforge.net/recount/ExpressionSets/montpick_eset.RData")
load(file = con)
close(con)
mp = montpick.eset
pdata_mp = pData(mp)
edata_mp = exprs(mp)

```

```{r}
library(devtools)
library(Biobase)
library(dendextend)

kmeans = kmeans(edata_mp, centers = 3)
kmeans2 = kmeans(edata_mp[rowMeans(edata_mp) < 100,], centers = 3)
kmeans3 = kmeans(log2(edata + 1), centers = 3)
matplot(t(kmeans$centers),col=1:3,type="l",lwd=3)
matplot(t(kmeans2$centers), col = 1:3, type = "l", lwd = 3)
matplot(t(kmeans3$centers), col = 1:3, type = "l", lwd = 3)

plot(kmeans$centers)
```


```{r}

set.seed(1235)
kmeans4 = kmeans(log2(edata_mp + 1), centers = 2)

dist = dist(t(edata_mp)) #[ , -which(colnames(edata_mp) == "NA18853") ]
dend = hclust(dist)
cut<- cutree(dend, k = 2)

matplot(t(kmeans4$centers), col=1:2,type="l",lwd=3); plot(dend);plot(cut, pch = kmeans4$cluster )
```